### ISSUE TITLE
Can’t get CSS injection to work on Todoist.com

### ISSUE THREAD

**Issue by champagnealexandre** [jiahaog/nativefier#1297]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [X] I searched existing issues, open & closed. Yes, my question is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

I can’t seem to get CSS injection to work on domain Todoist.com. It works fine in Chrome, so I’m a bit puzzled. Can somebody help? I’ve used CSS injection in the past with other websites and had no problem whatsoever. Also tried clearing app data in the nativefied app, doesn’t change anything.

**Steps to reproduce**

There is no error message. For example,

```
nativefier --verbose nativefier 'https://todoist.com/' --name Todoist _temp --inject /Users/alexandre/drive/informatique/todoist.css
URL "nativefier" lacks a protocol. Will try to parse it as HTTPS: "https://nativefier". Please pass "http://nativefier" if this is what you meant.
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform darwin

Performing async options post-processing.
Inferring icon for https://nativefier/ on darwin
Inferring icon from store for https://nativefier/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Sanitized filename for Todoist : Todoist
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Cannot automatically retrieve the app icon: Error: getaddrinfo ENOTFOUND nativefier
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'nativefier',
  config: {
    url: 'https://nativefier/',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'nativefier',
      port: null,
      nativeProtocols: [Object],
      pathname: '/'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET / HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: nativefier\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'nativefier',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://nativefier/',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/local/Cellar/nativefier/45.0.0/libexec/lib/node_modules/nativefier/app',
    electronVersion: '13.1.7',
    icon: undefined,
    name: 'Todoist',
    out: 'https://todoist.com/',
    overwrite: true,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://nativefier/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'Todoist',
      InternalName: 'Todoist',
      FileDescription: 'Todoist'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [ '/Users/alexandre/drive/informatique/todoist.css' ],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '45.0.0',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/local/Cellar/nativefier/45.0.0/libexec/lib/node_modules/nativefier/app to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V
Writing app config to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V/nativefier.json
Copying 1 files to inject in app.
Copying injection file "/Users/alexandre/drive/informatique/todoist.css" to "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V/inject/inject-318b14.css"
Updating /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V/package.json 'name' field to todoist-nativefier-c59461

Converting icons...
Option "icon" not set, skipping icon conversion.
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.3.0
  electron-packager Node v14.17.3
  electron-packager Host Operating system: darwin 20.6.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V","electronVersion":"13.1.7","name":"Todoist","out":"https://todoist.com/","overwrite":true,"platform":"darwin","portable":false,"targetUrl":"https://nativefier/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"Todoist","InternalName":"Todoist","FileDescription":"Todoist"}} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-2-12-app--5065-lXUbI2biOC9V/package.json +0ms
  electron-packager Application name: Todoist +4ms
  electron-packager Target Electron version: 13.1.7 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"13.1.7","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v13.1.7
  electron-packager Creating /Users/alexandre/Applications/Nativefier apps/https:/todoist.com/darwin-x64-template +2ms
  electron-packager Extracting /Users/alexandre/Library/Caches/electron/c02b94db45d0f83639398d95d22e41e09fd3474003678b9f728c6d3f2a93193c/electron-v13.1.7-darwin-x64.zip to /Users/alexandre/Applications/Nativefier apps/https:/todoist.com/darwin-x64-template +1ms
  electron-packager Initializing app in https:/todoist.com/Todoist-darwin-x64 from /Users/alexandre/Applications/Nativefier apps/https:/todoist.com/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/Users/alexandre/Applications/Nativefier apps/https:/todoist.com' ] +1s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +0ms
  electron-packager Validation complete +1ms
  electron-packager Renaming Electron to Todoist in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/MacOS +29ms
  electron-packager Renaming Electron Helper to Todoist Helper in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Renderer) to Todoist Helper (Renderer) in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (Plugin) to Todoist Helper (Plugin) in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Todoist Helper (GPU) in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Todoist Helper.app in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper (Renderer).app to Todoist Helper (Renderer).app in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Todoist Helper (Plugin).app in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (GPU).app to Todoist Helper (GPU).app in https:/todoist.com/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to https:/todoist.com/Todoist-darwin-x64, move to wherever it makes sense for you and run the app bundle.
```

**Debug info**

Here’s my CSS injection. Simple cosmetic changes.

```
.board_view__sections {
    padding: 0 5px 8px !important;
}

.board_task {
    width: 260px !important;
    margin: 0 0 2px !important;
    padding: 2px !important;
    border: 1px solid rgba(0,0,0,.12) !important;
    border-radius: 5px !important;
}

.board_section__task_list {
    padding: 0 2px !important;
}

.board_section {
    width: 280px !important;
    padding: 0 !important;
    margin-right: 2px !important;
    border: 1px solid transparent !important;
    border-radius: 1px !important;
}

.board_section {
    width: 270px !important;
    padding: 0 !important;
    margin-right: 2px !important;
    border: 1px solid transparent !important;
    border-radius: 1px !important;
}

.board_section__header {
    width: 268px !important;
    padding-right: 2px !important;
    padding-left: 8px !important;
    border-bottom: 1px solid transparent !important;
}

.view_header {
    padding-left: 10px !important;
}

.view_header .view_header__content {
    padding-bottom: 8px !important;
    max-width: 2000px !important;
    margin: 0 10px !important;
    border-bottom: 1px solid transparent !important;
}

.view_options_status {
    margin: 0 10px !important;
    padding: 0 10px !important;
    max-width: 2000px !important;
}
```

**Context**

 - Nativefier: 45.0.0
 - Node.js: 14.17.3
 - Npm: 6.14.13
 - OS: macOS Big Sur 11.6 (20G165)
 - Additional context: nothing I can think of

**Comment by champagnealexandre** [comment]
My bad, the one I posted was indeed wrongly formatted. But trying again with the one you suggested produces the same behavior.

**Comment by TheCleric** [comment]
@champagnealexandre This seems to be working fine for me. I modified your CSS slightly to be a bit more obvious, and I am seeing the CSS be injected on the latest Nativefier (45.0.4). Try this and see if the background colors show up. If so, the CSS is getting injected:

```css
.board_section {
  width: 270px !important;
  padding: 0 !important;
  margin-right: 2px !important;
  border: 1px solid transparent !important;
  border-radius: 1px !important;
  background-color: blue !important;
}

.board_section__header {
  width: 268px !important;
  padding-right: 2px !important;
  padding-left: 8px !important;
  border-bottom: 1px solid transparent !important;
  background-color: purple !important;
}

.board_section__task_list {
  padding: 0 2px !important;
  background-color: orange !important;
}

.board_task {
  width: 260px !important;
  margin: 0 0 2px !important;
  padding: 2px !important;
  border: 1px solid rgba(0, 0, 0, 0.12) !important;
  border-radius: 5px !important;
  background-color: yellow !important;
}

.board_view__sections {
  padding: 0 5px 8px !important;
  background-color: lightpink !important;
}

.view_header {
  padding-left: 10px !important;
  background-color: green !important;
}

.view_header .view_header__content {
  padding-bottom: 8px !important;
  max-width: 2000px !important;
  margin: 0 10px !important;
  border-bottom: 1px solid transparent !important;
  background-color: red !important;
}

.view_options_status {
  margin: 0 10px !important;
  padding: 0 10px !important;
  max-width: 2000px !important;
  background-color: darkblue !important;
}
```
![Screen Shot 2021-10-29 at 3 28 57 PM](https://user-images.githubusercontent.com/547567/139491595-ec8f3490-5bc6-4993-9dd4-8fc55f869528.png)

![Screen Shot 2021-10-29 at 3 29 06 PM](https://user-images.githubusercontent.com/547567/139491623-31d348d8-9b97-4973-a15f-c7363acab318.png)

**Comment by champagnealexandre** [comment]
For some obscure reason the colors don’t show up neither. So the CSS really doesn’t get injected. Tried rebuilding the app, clearing app data, logging out/back in — nope.

I’ll investigate this further when I have a minute.

**Comment by TheCleric** [comment]
> For some obscure reason the colors don’t show up neither. So the CSS really doesn’t get injected. Tried rebuilding the app, clearing app data, logging out/back in — nope.
> 
> I’ll investigate this further when I have a minute.

What version of Nativefier are you running?

**Comment by champagnealexandre** [comment]
@TheCleric I’m using 45.0.0. I can try updating but not sure this will make a difference after reading the changelog.

One interesting thing I noticed: I’m using a Todoist app built with Fluid in the meantime, and opening the Fluid app sometimes reverts the webpage’s layout to the default one (i.e. without the CSS fixes I’ve included). Selecting "Reload from origin" in the Fluid app (whatever that means) reloads the page indeed, and the CSS fixes gets somehow re-applied.

I don’t have a clear explanation for this behavior though.

**Comment by champagnealexandre** [comment]
Tried updating nativefier to 45.0.4 and rebuilding the app, same behavior. Background stays white, even after clearing app data, logging out/back in, etc. Pretty much about to give up with nativefier at that point.

Here’s the logfile in case you’d see something to investigate:

```
[ 1 ] alexandre@Alexandres-MacBook-Pro Nativefier apps nativefier 'https://todoist.com/' --name Todoist _temp --inject /Users/alexandre/drive/informatique/todoist.css --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform darwin

Performing async options post-processing.
Inferring icon for https://todoist.com/ on darwin
Inferring icon from store for https://todoist.com/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Sanitized filename for Todoist : Todoist
Got 246 icons from gitcloud
Max icon match score: 1
Downloading https://nativefier.github.io/nativefier-icons/files/microsoft-todo.png
Got an icon from the page.
Writing 281.6 kb icon to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconinfer--9410-q7VuVhwYWQbd/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/local/lib/node_modules/nativefier/app',
    electronVersion: '13.4.0',
    icon: '/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconinfer--9410-q7VuVhwYWQbd/icon.png',
    name: 'Todoist',
    out: '_temp',
    overwrite: true,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://todoist.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'Todoist',
      InternalName: 'Todoist',
      FileDescription: 'Todoist'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [ '/Users/alexandre/drive/informatique/todoist.css' ],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '45.0.4',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/local/lib/node_modules/nativefier/app to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh
Writing app config to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh/nativefier.json
Copying 1 files to inject in app.
Copying injection file "/Users/alexandre/drive/informatique/todoist.css" to "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh/inject/inject-946458.css"
Updating /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh/package.json 'name' field to todoist-nativefier-409272

Converting icons...
Converting icon /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconinfer--9410-q7VuVhwYWQbd/icon.png to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconconv--9410-sFffCxkxJ4G9/icon.icns. Calling shell command: "/usr/local/lib/node_modules/nativefier/icon-scripts/convertToIcns" "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconinfer--9410-q7VuVhwYWQbd/icon.png" "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-iconconv--9410-sFffCxkxJ4G9/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout:
stderr: mktemp: too few X's in template ‘nativefier_icons’

    at iconShellHelper (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:46:11)
    at convertToIcns (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:83:10)
    at convertIconIfNecessary (/usr/local/lib/node_modules/nativefier/src/build/buildIcon.ts:87:37)
    at buildNativefierApp (/usr/local/lib/node_modules/nativefier/src/build/buildNativefierApp.ts:176:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.4.0
  electron-packager Node v14.17.3
  electron-packager Host Operating system: darwin 20.6.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh","electronVersion":"13.4.0","name":"Todoist","out":"_temp","overwrite":true,"platform":"darwin","portable":false,"targetUrl":"https://todoist.com/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"Todoist","InternalName":"Todoist","FileDescription":"Todoist"},"appBundleId":"com.electron.nativefier.todoist-nativefier-409272"} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-15-48-39-app--9410-aet5MDuFxOJh/package.json +0ms
  electron-packager Application name: Todoist +5ms
  electron-packager Target Electron version: 13.4.0 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"13.4.0","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v13.4.0
  electron-packager Creating /Users/alexandre/Applications/Nativefier apps/_temp/darwin-x64-template +2ms
  electron-packager Extracting /Users/alexandre/Library/Caches/electron/5b57a069ffc25b0ecdd42a0c95205b45b81fad3d78c81d7ecc9ab050d34f124d/electron-v13.4.0-darwin-x64.zip to /Users/alexandre/Applications/Nativefier apps/_temp/darwin-x64-template +1ms
  electron-packager Initializing app in _temp/Todoist-darwin-x64 from /Users/alexandre/Applications/Nativefier apps/_temp/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/Users/alexandre/Applications/Nativefier apps/_temp' ] +2s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +0ms
  electron-packager Validation complete +0ms
  electron-packager Renaming Electron to Todoist in _temp/Todoist-darwin-x64/Electron.app/Contents/MacOS +33ms
  electron-packager Renaming Electron Helper to Todoist Helper in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Renderer) to Todoist Helper (Renderer) in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (Plugin) to Todoist Helper (Plugin) in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Todoist Helper (GPU) in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Todoist Helper.app in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Todoist Helper (Renderer).app in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Todoist Helper (Plugin).app in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper (GPU).app to Todoist Helper (GPU).app in _temp/Todoist-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to _temp/Todoist-darwin-x64, move to wherever it makes sense for you and run the app bundle.
[ 1 ] alexandre@Alexandres-MacBook-Pro Nativefier apps
```
