### ISSUE TITLE
Issues with flash

### ISSUE THREAD

**Issue by jiahaog** [jiahaog/nativefier#152]
### Description

There might be some issues with the flash support. Nativefier tries to automatically determine where your local chrome installation is and gets the path to the PepperFlash plugin binary.

However, chrome is now on v48, while electron is on chrome v47, and hence this might cause some issues with flash. 

I've tried it out on https://helpx.adobe.com/flash-player.html and it seems to work, but your mileage may vary.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.9.1`
- Version of Node.js (run `$ node --version`): `v4.2.4`
- OS: `OSX 10.11.2`
- Architecture `64bit`

**Comment by ronjouch** [comment]
@jiahaog would you consider re-opening this? I see two problems:

1. I explicitly don't want flash, could the `--flash` argument support a `false` value?
2. Auto-detection seems to fail for users of the non-release Chrome channel, here is what I see due to using Chrome Beta, which for me on Ubuntu Linux installs to `/opt/google/chrome-beta`:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, scandir '/opt/google/chrome'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at findSyncRecurse (/opt/hipchat-linux-x64/resources/app/lib/webpack:/app/src/helpers/inferFlash.js:33
:29)
    at findSync (/opt/hipchat-linux-x64/resources/app/lib/webpack:/app/src/helpers/inferFlash.js:32:5)
    at linuxMatch (/opt/hipchat-linux-x64/resources/app/lib/webpack:/app/src/helpers/inferFlash.js:61:12)
    at inferFlash (/opt/hipchat-linux-x64/resources/app/lib/webpack:/app/src/helpers/inferFlash.js:17:16)
    at Object.<anonymous> (/opt/hipchat-linux-x64/resources/app/lib/webpack:/app/src/main.js:21:23)
    at __webpack_require__ (/opt/hipchat-linux-x64/resources/app/lib/webpack:/webpack/bootstrap 1aa06e4205
e3e37da886:19:1)
    at /opt/hipchat-linux-x64/resources/app/lib/webpack:/webpack/bootstrap 1aa06e4205e3e37da886:39:1
```

**Comment by jiahaog** [comment]
Yeah, I'll look into `1` in a bit. Actually nativefier does not bundle the flash binary but merely tries to find it and point electron to it.

I've also added a just added a hotfix in `6.10.1` 0ed5bd8c7bb599252f4e3a8aad6f21ffe6931abb which will fix the error in `2` if the directory is not found

**Comment by ronjouch** [comment]
@jiahaog fantastic, thanks! :)

**Comment by Phunky** [comment]
Can't seem to get this to work here on OSX 10.11, i've got Google Chrome installed via Homebrew Cask and defined the --flash location but receive a "Can not load plugin" error when viewing content.

Attempted on Twitch.tv and Netflix (although Netflix wouldn't even allow me to login).

**Comment by movestill** [comment]
I'm not having any problems with OS X El Capitan, but am having problems with Windows 7. The basic Adobe Flash page referenced above doesn't work. On OS X, I successfully nativefied Pandora so I can hook up the keyboard media buttons.

nativefier v7.0.1
nodejs v4.5.0
OS: Windows 7
architecture 64 bit
Pepper Flash v22.0.0.209
