### ISSUE TITLE
Error when trying to build for Windows on Linux

### ISSUE THREAD

**Issue by AgentSmith0** [jiahaog/nativefier#1563]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier --platform windows --arch x64 'https://example.org' builds/test --verbose

### Steps to reproduce

Try to build for Windows on Ubuntu 23.04 with wine installed.

### Expected behavior

Builds without any errors.

### Actual behavior

Builds fails and I get the following error message:
```
Error during build. Run with --verbose for details. WrapperError: Wrapper command 'wine64' not found on the system. Consult your Linux distribution's package manager to determine how to install Wine.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.
```

### Debug info

```
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
rawOptions {
  _: [ 'https://example.org', 'builds/test' ],
  platform: 'windows',
  p: 'windows',
  arch: 'x64',
  a: 'x64',
  verbose: true,
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'disable-dev-tools': false,
  disableDevTools: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  'single-instance': false,
  singleInstance: false,
  tray: 'false',
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'strict-internal-urls': false,
  strictInternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  quiet: false,
  '$0': 'nativefier',
  targetUrl: 'https://example.org',
  out: 'builds/test'
}
Normalized URL https://example.org to: https://example.org/
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring icon for https://example.org/ on win32
Inferring icon from store for https://example.org/ on win32
Allowed icon formats when building for win32: [ '.ico', '.png' ]
Inferring name for https://example.org/
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .ico icon from the page.
Fetched 1.2 kb page at https://example.org/
Inferred title: Example Domain
Sanitized filename for Example Domain : Example Domain
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/lib/node_modules/nativefier/app',
    electronVersion: '21.4.4',
    icon: undefined,
    name: 'Example Domain',
    out: 'builds/test',
    overwrite: true,
    quiet: false,
    platform: 'win32',
    portable: false,
    targetUrl: 'https://example.org/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: undefined,
      InternalName: undefined,
      FileDescription: undefined
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '51.0.1',
    quiet: false,
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    strictInternalUrls: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/lib/node_modules/nativefier/app to /tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER
Writing app config to /tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER/nativefier.json {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  appBundleId: undefined,
  appCategoryType: undefined,
  appCopyright: undefined,
  appVersion: undefined,
  arch: 'x64',
  asar: false,
  backgroundColor: undefined,
  basicAuthPassword: undefined,
  basicAuthUsername: undefined,
  blockExternalUrls: false,
  bounce: false,
  browserwindowOptions: undefined,
  buildDate: 1692261508714,
  buildVersion: undefined,
  clearCache: false,
  counter: false,
  crashReporter: undefined,
  darwinDarkModeSupport: false,
  derefSymlinks: undefined,
  disableContextMenu: false,
  disableDevTools: false,
  disableGpu: false,
  disableOldBuildWarning: false,
  diskCacheSize: undefined,
  download: undefined,
  electronVersionUsed: '21.4.4',
  enableEs3Apis: false,
  executableName: undefined,
  fastQuit: false,
  fileDownloadOptions: undefined,
  flashPluginDir: undefined,
  fullScreen: false,
  globalShortcuts: undefined,
  height: 800,
  helperBundleId: undefined,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  internalUrls: undefined,
  isUpgrade: false,
  junk: undefined,
  lang: undefined,
  maximize: false,
  maxHeight: undefined,
  maxWidth: undefined,
  minHeight: undefined,
  minWidth: undefined,
  name: 'Example Domain',
  nativefierVersion: '51.0.1',
  osxNotarize: undefined,
  osxSign: undefined,
  portable: false,
  processEnvs: undefined,
  protocols: undefined,
  proxyRules: undefined,
  prune: undefined,
  quiet: false,
  showMenuBar: false,
  singleInstance: false,
  strictInternalUrls: false,
  targetUrl: 'https://example.org/',
  titleBarStyle: undefined,
  tray: 'false',
  usageDescription: undefined,
  userAgent: undefined,
  userAgentHonest: false,
  versionString: undefined,
  width: 1280,
  widevine: false,
  win32metadata: {
    ProductName: undefined,
    InternalName: undefined,
    FileDescription: undefined
  },
  x: undefined,
  y: undefined,
  zoom: 1,
  oldBuildWarningText: ''
}
No files to inject, skipping copy.
Updating /tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER/package.json 'name' field to example-domain-nativefier-ef57f6

Converting icons...
Option "icon" not set, skipping icon conversion.
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.5.2
  electron-packager Node v18.17.1
  electron-packager Host Operating system: linux 6.2.0-26-generic (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER","electronVersion":"21.4.4","name":"Example Domain","out":"builds/test","overwrite":true,"quiet":false,"platform":"win32","portable":false,"targetUrl":"https://example.org/","tmpdir":false,"upgrade":false,"win32metadata":{},"appBundleId":"com.electron.nativefier.example-domain-nativefier-ef57f6"} +0ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Requiring author in package.json, as CompanyName was not specified for win32metadata +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER/package.json +6ms
  electron-packager Inferring win32metadata.CompanyName from author in /tmp/nativefier-10-38-27-app--2116672-lbVvc7VoTdER/package.json +0ms
  electron-packager Application name: Example Domain +7ms
  electron-packager Target Electron version: 21.4.4 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/node_gyp_bins($|/)',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"21.4.4","artifactName":"electron"} +0ms
Packaging app for platform win32 x64 using electron v21.4.4
  electron-packager Creating /home/user/builds/test/win32-x64-template +4ms
  electron-packager Extracting /home/user/.cache/electron/4886f6bdfbece03c76c6580ac4e70991fd4f8e6a260917d2cc919cccbf03edfb/electron-v21.4.4-win32-x64.zip to /home/user/builds/test/win32-x64-template +1ms
  electron-packager Initializing app in builds/test/Example Domain-win32-x64 from /home/user/builds/test/win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/home/user/builds/test' ] +3s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +0ms
  electron-packager Validation complete +2ms
  electron-packager Renaming electron.exe to Example Domain.exe in builds/test/Example Domain-win32-x64 +58ms
  electron-packager Running rcedit with the options {"version-string":{"OriginalFilename":"Example Domain.exe","CompanyName":"Jia Hao"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms
Error during build. Run with --verbose for details. WrapperError: Wrapper command 'wine64' not found on the system. Consult your Linux distribution's package manager to determine how to install Wine.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.

See https://github.com/electron/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at spawnWrapper (/usr/lib/node_modules/nativefier/node_modules/cross-spawn-windows-exe/src/wrapper.ts:90:13)
    at module.exports (/usr/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:42:3)
    at WindowsApp.runRcedit (/usr/lib/node_modules/nativefier/node_modules/electron-packager/src/win32.js:95:7)
    at WindowsApp.create (/usr/lib/node_modules/nativefier/node_modules/electron-packager/src/win32.js:105:5)
    at async Promise.all (index 0)
    at packager (/usr/lib/node_modules/nativefier/node_modules/electron-packager/src/index.js:201:20)
    at buildNativefierApp (/usr/lib/node_modules/nativefier/src/build/buildNativefierApp.ts:211:24
```

### Nativefier version

51.0.1

### Node.js version

v18.17.1

### npm version

9.8.1

### OS

Ubuntu Server 23.04 (Linux 6.2.0-26-generic)

**Comment by akliewer99** [comment]
Hi AgentSmith, I had a similar issue, but I was able to install Wine after activating 32-bit mode.
`sudo dpkg --add-architecture i386`
Then Wine installed successfully.
`sudo apt install --install-recommends winehq-stable`
REF: [https://wiki.winehq.org/Ubuntu]

I am so close to it completing!!
Now my error is: "stderr: 'Unable to load file: "/mnt/c/Users/aklie/Repos-GIT/electron-nativefier/ism_localhost/dist/ISM_Local_Development-win32-x64/ISM_Local_Development.exe"\r\n',
  code: 1"
- It creates the directory, the resources, and even the "exe" file but then stops with above error.
A real bummer!
![Screenshot 2023-08-20 122123 (800)](https://github.com/nativefier/nativefier/assets/1025723/2a60ab92-582e-4a42-8255-4b06028c0176)
