### ISSUE TITLE
nativefier is not executable - returns SyntaxError stacktrace

### ISSUE THREAD

**Issue by CodeBrauer** [jiahaog/nativefier#215]
### Description
nativefier is not executable - returns SyntaxError stacktrace.

Running `nativefier` returns the attached stacktrace.

### Steps to Reproduce Issue
`$ nativefier https://github.com`

### Specifications
- Version - today installed `7.0.0` // `nativefier --version` -> see stracktrace
- Version of Node.js: `v0.10.40`
- OS: `OS X 10.10.5`
- Architecture `Darwin x64`
- Stack trace from the error message (if any)

```
/Users/gw/.nvm/v0.10.40/lib/node_modules/nativefier/node_modules/electron-packager/index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/source/build/buildMain.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by tmuplayer33** [comment]
I had the same issue. This fixed it for me: http://stackoverflow.com/a/35218558

**Comment by CodeBrauer** [comment]
@tmuplayer33 - I tried this already - but this didn't change anything.

**Comment by jiahaog** [comment]
@CodeBrauer You need node.js >=4 to run Nativefier due to the limitations of electron packager

**Comment by CodeBrauer** [comment]
Thanks. Didn't see that i had [`nvm`](https://github.com/creationix/nvm) and [`n`](https://github.com/tj/n) and it kinda battled. Works now fine.
