### ISSUE TITLE
Nativefier broken, does not work anymore

### ISSUE THREAD

**Issue by Oliver88** [jiahaog/nativefier#216]
### Description

All of a sudden Nativefier stopped working. I tried to update nativefier to the newest version, nothing :/

nativefier spits out an error everytime you try to build an app, even with `$ nativefier --version`.

### Specification:

```
$ nativefier --version
/usr/local/lib/node_modules/nativefier/node_modules/electron-packager/index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/build/buildMain.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I really hope this can be fixed!

**Comment by Oliver88** [comment]
Ok, could fix it by using this one [](http://stackoverflow.com/a/35218558).
Sorry, could have looked up this solution earlier, I didn´t see there was a similar issue.
