### ISSUE TITLE
Tests fail with `Error: Could not find "wine" on your system`.

### ISSUE THREAD

**Issue by githubbob42** [jiahaog/nativefier#245]
### Description

Tests fail with `Error: Could not find "wine" on your system`.

Obviously, if I have `wine` installed, it works.  I do actually have `wine` installed, I just renamed it to test a theory -  I have a PR https://github.com/jiahaog/nativefier/pull/244 that is failing it's test for the exact same reason.  Unfortunately, I don't have any control over the CI server so I wanted to make sure it wasn't my code that was causing the failures so I cloned from scratch to test if a clean install also fails and it does.
### Steps to Reproduce Issue

```
$ git clone https://github.com/jiahaog/nativefier.git
$ cd nativefier
$ npm run dev-up
$ npm run build
$ npm test
```
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v6.3.1`
- OS: `OSX 10.11.6`
- Architecture `x64`
- Stack trace from the error message (if any)

```
~/Projects/nativefier_test (development)$ npm test

> nativefier@7.0.1 test /Users/broth/Projects/nativefier_test
> gulp test

[15:34:12] Requiring external module babel-register
[15:34:13] Using gulpfile ~/Projects/nativefier_test/gulpfile.babel.js
[15:34:13] Starting 'test'...
[15:34:13] Starting 'prune'...
[15:34:15] Finished 'prune' after 1.68 s
[15:34:15] Starting 'build'...
[15:34:15] Starting 'clean'...
[15:34:15] Finished 'clean' after 21 ms
[15:34:15] Starting 'build-cli'...
[15:34:15] Starting 'build-static-js'...
[15:34:15] Starting 'build-static-not-js'...
[15:34:15] Starting 'build-tests'...
[15:34:15] Finished 'build-static-not-js' after 487 ms
[15:34:15] Finished 'build-static-js' after 601 ms
[15:34:15] Starting 'build-static'...
[15:34:15] Finished 'build-static' after 3.35 μs
[15:34:15] Starting 'build-app'...
[15:34:16] Finished 'build-tests' after 1.01 s
[15:34:17] Version: webpack 1.13.2
      Asset    Size  Chunks             Chunk Names
    main.js  139 kB       0  [emitted]  main
main.js.map  173 kB       0  [emitted]  main
[15:34:17] Finished 'build-app' after 1.14 s
[15:34:17] Finished 'build-cli' after 1.78 s
[15:34:17] Finished 'build' after 1.8 s
[15:34:17] Starting 'mocha'...

  Get Icon Module
    ✓ Can convert icons

  Nativefier Module
Packaging app for platform darwin x64 using electron v1.1.3
Packaging app for platform linux x64 using electron v1.1.3
  packaging [================================                  ] 63%Packaging app for platform win32 x64 using electron v1.1.3
    1) Can build an app from a target url

  Infer User Agent
    ✓ Can infer userAgent for all platforms (320ms)
    ✓ Connection error will still get a user agent (5004ms)


  3 passing (12s)
  1 failing

  1) Nativefier Module Can build an app from a target url:
     Error: Could not find "wine" on your system.

Wine is required to use the app-copyright, app-version, build-version, icon, and 
version-string parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
      at exports._errnoException (util.js:1012:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
      at onErrorNT (internal/child_process.js:348:16)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: 1 test failed.
npm ERR! Test failed.  See above for more details.
```

**Comment by vrunjeti** [comment]
I also failed the travis ci tests in #258 for the same reason, and I only changed the docs

**Comment by ronjouch** [comment]
@jiahaog fixed the Travis tests with https://github.com/jiahaog/nativefier/commit/c362108c738993c2e9407bc38417bfb7670977a9 😺. Closing.
