### ISSUE TITLE
Nativefier Broken

### ISSUE THREAD

**Issue by spencerthayer** [jiahaog/nativefier#255]
### Description
Nativefier doesn't work at all after following installation instructions.

### Steps to Reproduce Issue
Install and type "nativefier" in command.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v0.0.0`
Cannot due to being broken.
- Version of Node.js (run `$ node --version`): `v0.0.0`
v0.12.7
- OS: `<OS>`
OS X 10.10.5 (14F1909)
```
$ nativefier
/usr/local/lib/node_modules/nativefier/node_modules/electron-packager/index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/source/build/buildMain.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by hedinfaok** [comment]
@spencerthayer I just had the same problem. My node was too old.  After updating to the latest version, everything worked great.

**Comment by spencerthayer** [comment]
Upgrading to 6.5.0 fixed this issue @hedinfaok. Thanks!

**Comment by Jbithell** [comment]
+1
Updating Node resolves this issue
