### ISSUE TITLE
OSX: can't use, because of 404 missing https://github.com/electron/electron/releases/download/vbitbucket_link/electron-vbitbucket_link-darwin-x64.zip

### ISSUE THREAD

**Issue by teamgroove** [jiahaog/nativefier#298]
when trying to use: nativefier on the cmdline the following error occurs:

Downloading electron-vbitbucket_link-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/vbitbucket_link/electron-vbitbucket_link-darwin-x64.zip returned 404

Error: Failed to find Electron vbitbucket_link for darwin-x64 at https://github.com/electron/electron/releases/download/vbitbucket_link/electron-vbitbucket_link-darwin-x64.zip
    at Request.<anonymous> (/Users/rt/.nvm/versions/node/v6.5.0/lib/node_modules/nativefier/node_modules/nugget/index.js:170:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/rt/.nvm/versions/node/v6.5.0/lib/node_modules/nativefier/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
  packaging [========================================          ] 

Strangely it seems to work when explicit setting cmdline-parameter: -p
Something like:

works
nativefier -p osx -name helloworld http://www.example.com

doesn't work
nativefier -name helloworld http://www.example.com

**Comment by teamgroove** [comment]
I am very sorry, the problem was in front of the monitor.
instead of the parameter: -n
i used: -name
which is wrong, should have been: --name
this choked on the next parameter: -p osx

If used correctly, there is no issue. MAybe the parameters could be validated better, and the corresponding error-message. But it's definately no issue. My error. Sorry.
