### ISSUE TITLE
Bug when trying to create an app

### ISSUE THREAD

**Issue by clang676** [jiahaog/nativefier#313]
C:\Users\Charles>      **nativefier --name "Asana" "https://app.asana.com"**

C:\Users\Charles\AppData\Roaming\npm\node_modules\nativefier\node_modules\electron-packager\index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\source\build\buildMain.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

### Specifications
- Version of Nativefier (run `$ nativefier --version`): 
   `C:\Users\Charles>nativefier --version

C:\Users\Charles\AppData\Roaming\npm\node_modules\nativefier\node_modules\electron-packager\index.js:3
const common = require('./common')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\source\build\buildMain.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`
- Version of Node.js (run `$ node --version`): `v0.10.24`
- OS: `WINDOWS 10`

**Comment by clang676** [comment]
Corrected issue by updating to latest version of node
