### ISSUE TITLE
Mac OSX Error Opening App When Signed & Downloaded From Web

### ISSUE THREAD

**Issue by jasonivers** [jiahaog/nativefier#428]
### Description

I used nativefier to build an app.  It works fine locally, but not if downloaded from the web, which requires it to be signed.

I signed the app and all of the framework stuff with a modified version of this shell script:  http://jbavari.github.io/blog/2015/08/14/codesigning-electron-applications/

This got me past the "must be signed" problem, but I get a new issue now, about a read only file system (full text of error below).

### Steps to reproduce issue

Build the nativefier app (command line below)
Sign the nativefier app (see full code used to do so at bottom)
Upload the app somewhere
Download the app over the web
Uncompress zip file
Open app

### Details

- Are you nativefying a *public* website? No... it is restricted, but this is not an error from the site (hasn't even gotten to the point of opening the site).
- Feature request? N/A
- Full nativefier command used to build your app: `nativefier --app-bundle-id="com.enginato.mac-desktop" --name="EnginatoDev" --platform=darwin --icon=/Users/jason/wedo/public/images/logos/app_icon.png --counter --fast-quit --maximize --disable-context-menu --disable-dev-tools "http://dev.enginato.com/chat?native_app=true"  --arch=x64 --app-version="0.1.0" --build-version="0.1.0" --single-instance`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v8.3.0`
- OS: `OSX 10.12.6`
- Error message / stack trace (if any):

```
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/g6/_6gc9ydx59v8pz145fngsw1w0000gn/T/AppTranslocation/64491CC6-AEC6-4D6B-BDE5-9FAF1A86D317/d/EnginatoDev.app/Contents/Resources/app/nativefier.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at createMainWindow (/private/var/folders/g6/_6gc9ydx59v8pz145fngsw1w0000gn/T/AppTranslocation/64491CC6-AEC6-4D6B-BDE5-9FAF1A86D317/d/EnginatoDev.app/Contents/Resources/app/lib/webpack:/app/src/components/mainWindow/mainWindow.js:95:8)
    at App.<anonymous> (/private/var/folders/g6/_6gc9ydx59v8pz145fngsw1w0000gn/T/AppTranslocation/64491CC6-AEC6-4D6B-BDE5-9FAF1A86D317/d/EnginatoDev.app/Contents/Resources/app/lib/webpack:/app/src/main.js:90:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

Signing code:
```
# Invoke this script with a relative `.app` path
# EX:
# codesign.sh "dist/osx/MyApp-darwin-x64/MyApp.app"

#Run the following to get a list of certs
# security find-identity
app="$PWD/$1"
app_file_name=${app##*/}
app_name=${app_file_name%.*}
identity="BC58B02CB89661AFAED42F7DC833A6F975F6E855"

echo "### signing frameworks"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Electron Framework.framework/Electron Framework"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Electron Framework.framework/"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Electron Framework"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/$app_name Helper EH.app/Contents/MacOS/$app_name Helper EH"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/$app_name Helper NP.app/Contents/MacOS/$app_name Helper NP"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/$app_name Helper NP.app/Contents/MacOS/$app_name Helper NP"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/EnginatoDev Helper.app/Contents/MacOS/EnginatoDev Helper"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Mantle.framework/Mantle"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Mantle.framework/Versions/A"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/ReactiveCocoa.framework/ReactiveCocoa"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Squirrel.framework/Squirrel"
codesign --deep --force --verify --verbose --sign "$identity" "$app/Contents/Frameworks/Squirrel.framework/Versions/A"

echo "### signing app"
codesign --deep --force --verify --verbose --sign "$identity" "$app"


echo "### Zipping app"
ditto -c -k --sequesterRsrc --keepParent $app/ ./enginato_mac.zip

echo "### verifying signature",
codesign -vvvv -d "$app"
spctl -a -vvvv "$app"
```

**Comment by jasonivers** [comment]
This appears to be an issue with opening the app from the "Downloads" folder (default when saving an app in Chrome on OSX, at least, not sure about other browsers).  The app has to be copied to the "Applications" folder first.

It looks like it might be worth building/merging/whatever a tool that creates a setup/install file to do this for you.

**Comment by mattruzzi** [comment]
Apps downloaded from the web have the com.apple.quarantine extended attribute. You can remove it using 
`xattr -r -d com.apple.quarantine /path/to/example.app`
