### ISSUE TITLE
Cannot find module 'wurl'

### ISSUE THREAD

**Issue by Bloodyaugust** [jiahaog/nativefier#44]
On Ubuntu 15.04 32-bit, while trying to run the result of `nativefier --pretend "http://google.com" -n Google`.

Full error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'wurl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/anonymized/Code/Google-linux-ia32/resources/app/main.js:9:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/anonymized/Code/Google-linux-ia32/resources/atom.asar/browser/lib/init.js:159:8)

```

**Comment by greg-js** [comment]
Whoa, I was just about to post the same exact issue right now!

Anyway, a temporary workaround is to go into the nativefier directory and then do an `npm install` in ./app, then reinstall the app, it will work then.

**Comment by jiahaog** [comment]
There seems to be something wrong with the missing module, I'm looking into it now

**Comment by kinggrowler** [comment]
I get the same JavaScript error about the missing module wurl on Mac OS 10.9.5. I installed npm via brew, and @greg-js workaround worked for me. I cd'd into "/usr/local/lib/node_modules/nativefier/app"; did "npm install", which installed wurl, then re-created my nativifier app.

```
$ npm install
nativefier-placeholder@1.0.0 /usr/local/lib/node_modules/nativefier/app
`-- wurl@2.1.0
```

**Comment by jiahaog** [comment]
Alright it should be fixed now. I'm not sure why even though I committed the wurl in the `/app/node_module`, it doesn't get pulled down when we do `npm install -g nativefier`. I'm actually not very happy with how modules have to be committed, and a cleaner build system would be better in the long run.

**Comment by Bloodyaugust** [comment]
Confirmed fix. Thanks for the quick response!
