### ISSUE TITLE
Unable to inject resources during programmatic build

### ISSUE THREAD

**Issue by legowerewolf** [jiahaog/nativefier#443]
### Description

I'm trying to use the programmatic API as a simple way to define an app's configuration for building without having to worry about saving commands. I'm having problems with injecting a script using this API. As a side note, the app will build just fine from the command line.

### Steps to reproduce issue
1. Extract [IITC.zip](https://github.com/jiahaog/nativefier/files/1279690/IITC.zip)
1. Run `npm install` inside the new directory to fetch dependencies.
1. Run `node build.js`

Try removing the `inject` line and running `node build.js` again. It builds fine for me then, but without the script I want.

### Details

- Full nativefier command used to build your app: `node build.js`
- Version of Nativefier: `v7.4.1`
- Version of node.js: `v8.1.2`
- OS: `Windows 10 Home, version 1703, build 15063.540`
- Error message / stack trace (if any):

```
C:\Users\Legowerewolf\Development\Workspaces\WebApps-native\test>node build.js
  copying [==========                                        ] 20%
C:\Users\Legowerewolf\Development\Workspaces\WebApps-native\test\node_modules\nativefier\lib\build\build\buildApp.js:52
  const promises = srcs.map(src => new Promise((resolve, reject) => {
                        ^
TypeError: srcs.map is not a function
    at maybeCopyScripts (C:\Users\Legowerewolf\Development\Workspaces\WebApps-native\test\node_modules\nativefier\lib\build\build\buildApp.js
:52:25)
    at C:\Users\Legowerewolf\Development\Workspaces\WebApps-native\test\node_modules\nativefier\lib\build\build\buildApp.js:123:5
    at cb (C:\Users\legowerewolf\Development\Workspaces\WebApps-native\test\node_modules\ncp\lib\ncp.js:255:37)
    at WriteStream.<anonymous> (C:\Users\Legowerewolf\Development\Workspaces\WebApps-native\test\node_modules\ncp\lib\ncp.js:133:14)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:579:14)
    at afterWrite (_stream_writable.js:431:3)
    at onwrite (_stream_writable.js:421:7)
    at fs.js:2133:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:690:5)
```

**Comment by omidfi** [comment]
I had the same problem, giving it an array will solve it

    inject: [ './custom-scripts.js']
