### ISSUE TITLE
rstudio server pop-up windows won't load

### ISSUE THREAD

**Issue by leipzig** [jiahaog/nativefier#466]
### Description

RStudio server comes with its web server that normally runs on 8787

### Steps to reproduce issue
download, install, deploy rstudio server
https://www.rstudio.com/products/rstudio/download-server/

Natify website `http://whatever:8787`

Click on `git` tab and commit a file (will attempt to open a window). Window loading spinner will spin forever. Javascript error is visible with developer tools.

might be related to https://github.com/jiahaog/nativefier/issues/408
### Details

- Are you nativefying a *public* website?
no

- Full nativefier command used to build your app: `nativefier --name "RStudioServer" "http://mywebsite.com:8787"`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v8.1.2`
- OS: `10.12.6`
- Error message / stack trace (if any):

```
Uncaught TypeError: $wnd.opener.registerAsRStudioSatellite is not a function
    at s9e (rstudio-1.js:1658:772)
    at r9e (rstudio-1.js:1141:27)
    at I9e (rstudio-1.js:1437:27)
    at doe.eoe [as wj] (rstudio-1.js:1685:157315)
    at d7h.e7h [as Cq] (rstudio-24.js:3981:297861)
    at Gfd.Hfd [as vj] (rstudio-0.js:9459:7010)
    at yl (rstudio-0.js:8079:79)
    at nl (rstudio-0.js:6688:60)
    at Bl.Cl [as vj] (rstudio-0.js:9455:13630)
    at wl (rstudio-0.js:1386:25)

```

**Comment by derekpowell** [comment]
I'm also having a similar issue. When editing an Rmarkdown file and attempting to open a plot in a separate window, the window shows the loading wheel forever. Interestingly though, when I open a plot generated from the console with the "Zoom" button in the Plots pane, it works just fine. Maybe that's a clue?

**Comment by zacharylawrence** [comment]
> I'm also having a similar issue. When editing an Rmarkdown file and attempting to open a plot in a separate window, the window shows the loading wheel forever. Interestingly though, when I open a plot generated from the console with the "Zoom" button in the Plots pane, it works just fine. Maybe that's a clue?

I just wanted to note that I'm experiencing the same issue. "Zoom" in the Plots pane works fine but "Show in New Window" when viewing a table creates a new window that spins forever.

**Comment by malcolmbarrett** [comment]
Anyone had any luck with a workaround for this bug?
