### ISSUE TITLE
Error: Command failed: npm prune --production

### ISSUE THREAD

**Issue by pixelass** [jiahaog/nativefier#492]
### Description
Error when nativefying 

### Steps to reproduce issue

```
yarn global add nativefier
nativefier web.whatsapp.com
```

### Details

- OS X 10.12.6 (16G29)

```
15:38 $ nativefier web.whatsapp.com
  packaging [================================                  ] 65%Packaging app for platform darwin x64 using electron v1.6.6
{ Error: Command failed: npm prune --production
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'prune',
npm verb cli   '--production' ]
npm info using npm@5.4.2
npm info using node@v8.8.1
npm verb npm-session 90022823f41e449e
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm sill install loadIdealTree
npm sill install cloneCurrentTreeToIdealTree
npm sill install loadShrinkwrap
npm sill uninstall loadAllDepsIntoIdealTree
npm sill currentTree whatsapp-web-nativefier-7bbd2c@1.0.0
npm sill idealTree whatsapp-web-nativefier-7bbd2c@1.0.0
npm sill install generateActionsToTake
npm sill diff-trees filtering actions: includeDev false includeProd true
npm sill diffTrees action count 0
npm sill decomposeActions action count 0
npm sill install executeActions
npm sill doSerial global-install 0
npm verb correctMkdir /Users/greada/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/greada/.npm/_locks/staging-de85953acf983d44.lock for /Users/greada/Documents/workspace/WhatsApp Web-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.staging
npm sill doParallel extract 0
npm sill doReverseSerial unbuild 0
npm sill doSerial remove 0
npm sill doSerial move 0
npm sill doSerial finalize 0
npm sill doParallel refresh-package-json 0
npm sill doParallel preinstall 0
npm sill doSerial build 0
npm sill doSerial global-link 0
npm sill doParallel update-linked 0
npm sill doSerial install 0
npm sill doSerial postinstall 0
npm verb unlock done using /Users/greada/.npm/_locks/staging-de85953acf983d44.lock for /Users/greada/Documents/workspace/WhatsApp Web-darwin-x64/Electron.app/Contents/Resources/app/node_modules/.staging
npm sill install saveToDependencies
npm verb saving []
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb stack TypeError: log.notice is not a function
npm verb stack     at writeFileAtomic (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:195:17)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/write-file-atomic/index.js:50:11
npm verb stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb stack     at FSReqWrap.oncomplete (fs.js:137:15)
npm verb cwd /Users/greada/Documents/workspace/WhatsApp Web-darwin-x64/Electron.app/Contents/Resources/app
npm verb Darwin 16.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "prune" "--production"
npm verb node v8.8.1
npm verb npm  v5.4.2
npm ERR! log.notice is not a function
npm verb exit [ 1, true ]
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greada/.npm/_logs/2017-11-21T14_39_30_713Z-debug.log

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm prune --production' }
  packaging [========================================          ] 80%✔
```

**Comment by ronjouch** [comment]
Hi @pixelass, thanks for the feedback 👍. Can you globally yarn-uninstall nativefier and test installing it with npm instead?

**Comment by pixelass** [comment]
@ronjouch actually I did that initially and `nativefier` was not available so I installed it via yarn

**Comment by pixelass** [comment]
Node 8:

```
16:32 $ npm i nativefier -g
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   'nativefier',
npm verb cli   '-g' ]
npm info using npm@5.4.2
npm info using node@v8.8.1
npm verb npm-session 8e7b75e07fd8a449
npm sill install loadCurrentTree
npm sill install readGlobalPackageData
npm http fetch GET 200 https://registry.npmjs.org/nativefier 17ms (from cache)
npm sill fetchPackageMetaData error for [object Object] npa.resolve is not a function
npm verb stack TypeError: npa.resolve is not a function
npm verb stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:9:20)
npm verb stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:785:20)
npm verb stack     at tryOnImmediate (timers.js:747:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
npm verb cwd /Users/greada/Documents/workspace/s2/dekk
npm verb Darwin 16.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "nativefier" "-g"
npm verb node v8.8.1
npm verb npm  v5.4.2
npm ERR! npa.resolve is not a function
npm verb exit [ 1, true ]
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/greada/.npm/_logs/2017-11-21T15_33_05_581Z-debug.log
```

**Comment by ronjouch** [comment]
@pixelass nativefier should definitely be available through `npm`. npm5 < 5.5.1 is seriously barfed in many ways, can you first `npm install -g npm@5.5.1` ? (That doesn't change it looks like installing through yarn is broken, but just first checking with you a normal install works).

**Comment by pixelass** [comment]
I just retried with Node 6 and got it to work. Thank you
