### ISSUE TITLE
Error: rcedit.exe failed with exit code 1 and Fatal error: Unable to commit changes 

### ISSUE THREAD

**Issue by WinningRed** [jiahaog/nativefier#501]
### Description

Whenever it reached 60-65% it fails.

### Steps to reproduce issue
nativefier "http://maps.google.com" or any url

### Details

- Tried with a dozen sites
- Tried running in different directories
- Tries CMD, Bash

```
C:\WINDOWS\system32>nativefier "http://maps.google.com"
  packaging [===================================               ] 69%Packaging app for platform win32 x64 using electron v1.7.9
Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (C:\Users\hpp\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  packaging [========================================          ] 80%
```

**Comment by ronjouch** [comment]
@WinningRed thanks for the feedback. Sadly I can't reproduce the issue, could you:

- Provide *all* the information requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md)
- Try on another machine and help us isolate what could be causing the problem.

**Comment by serifreedom** [comment]
### Description

rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes

### Steps to reproduce issue

>nativefier "http://medium.com"

### Details

Q: Are you nativefying a *public* website?
A : Yes, but without domain name 
Q: Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
A : Yes
- Full nativefier command used to build your app: `nativefier "http://medium.com"`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v6.10.0`
- OS: `Windows`
![image](https://user-images.githubusercontent.com/1667960/33984034-cfddb698-e0e8-11e7-9da4-6c79d3592403.png)


```
Downloading tmp-15260-1-SHASUMS256.txt-1.7.9
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Packaging app for platform win32 x64 using electron v1.7.9
Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (C:\Users\neon\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by WinningRed** [comment]
I have got it fixed by using this command : 
cd C: or cd X where X is the path to folder. 
I was trying to build in C:\Windows\System32 but that's not possible as It is a Windows directory.

**Comment by onyet** [comment]
Upgrade Your Node Js... :)

**Comment by rkorebrits** [comment]
@onyet did that, but issue persits

**Comment by ronjouch** [comment]
Hi @rkorebrits. Following @WinningRed 's suggestion, can you try explicitly passing the output folder to somewhere you have access rights? For example,

```
nativefier --name "AppName" "https://*snip*" C:\Users\Richard\AppName
```

**Comment by rkorebrits** [comment]
Thanks @ronjouch 

I was already running the app from C:\Users\Richard\ and also ran the CMD as administrator. Tested with your suggestion, but no luck. No idea what is causing this.. I have reinstalled nativefier, but the same issue persists. 
Is it possible to generate a Windows package from Ubuntu? When I run it on my VM, it works fine, but only creates a package for linux

```
C:\Users\Richard>nvm use 8
8.0.0
Now using node v8.0.0 (64-bit)

C:\Users\Richard>nativefier --name "AppName" "https://***" C:\Users\Richard\AppName
  packaging [==============================                    ] 61%Packaging app for platform win32 x64 using electron v1.8.4
  packaging [===================================               ] 69%Error: rcedit.exe failed with exit code 1. Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Richard\AppData\Roaming\npm\node_modules\nativefier\node_modules\electron-packager\node_modules\rcedit\lib\rcedit.js:68:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  packaging [========================================          ] 80%
C:\Users\Richard>
```

**Comment by ronjouch** [comment]
> *"Is it possible to generate a Windows package from Ubuntu? When I run it on my VM, it works fine, but only creates a package for linux"*

@rkorebrits it is, you'll need WINE, and we also have rcedit trouble there ( https://github.com/jiahaog/nativefier/issues/375 ), but give it a try. You'll want to use flag `--platform windows` to enforce a target that is not the same as the build host.

**Comment by rkorebrits** [comment]
Okay. Is there no flag to do something with the icon? Just realised that I posted to a thread that has a different error code than mine

**Comment by rkorebrits** [comment]
`nativefier --name "googwin" "https://www.google.ca/"`

This worked however..

**Comment by easterneas** [comment]
I found another clue about this bug... it seems that it won't recognize icons that are inside the C drive (or boot drive, perhaps?). But, when I moved the same icon file from C drive into somewhere else (mine is E), it seems to be working just fine.

Seems like the `rcedit.exe` is the root cause of this bug, after all.

**Comment by abderrahman-teta** [comment]
change your build script take  a look at this
https://www.christianengvall.se/electron-packager-tutorial/
that work for me

**Comment by disetec21** [comment]
> Hi @rkorebrits. Following @winningred 's suggestion, can you try explicitly passing the output folder to somewhere you have access rights? For example,
> 
> ```
> nativefier --name "AppName" "https://*snip*" C:\Users\Richard\AppName
> ```

Great, thats the main problem, the directory final path

**Comment by raphadko** [comment]
Disabled Dropbox Sync and it worked. Some people disabled anti-virus. Just make sure no external process is locking/reading files.
