### ISSUE TITLE
Error: Unable to find a valid app

### ISSUE THREAD

**Issue by jingle0927** [jiahaog/nativefier#510]
1. nativefier --name "Wechat" "https://wx.qq.com/"
2. sudo electron-installer-debian --src /home/deepin/wechat-linux-x64/ --dest /home/deepin/wechat --arch amd64
3 . sudo dpkg -i wechat_1.0.0_amd64.deb 

deepin@deepin:~$ /usr/lib/wechat/wechat

But I Dclick /usr/lib/wechat/wechat is running，Dclick desktop file is not running.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/usr/lib/wechat/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/usr/lib/wechat/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)

```

**Comment by ronjouch** [comment]
@jingle0927 if the nativefied app runs but no longer does after being packaged by `electron-installer-debian`, then you should ask `electron-installer-debian` people, not Nativefier. When you do so, providing the text contents of the .desktop file will certainly help.
