### ISSUE TITLE
Nativefier doesn't work on Windows 7

### ISSUE THREAD

**Issue by subdan** [jiahaog/nativefier#511]
I've successfully installed nativefier by executing this command:
`npm install nativefier -g`
When I try to use nativefier I get this error:
```
> nativefier
ReferenceError: nativefier is not defined
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
>
```
This error appears only on Windows 7. On win 10 it works.

My OS is Windows 7
npm 5.5.1
node 8.9.1

How to run nativefier on Windows 7?

**Comment by subdan** [comment]
I've fixed the issue by restarting my PC.
