### ISSUE TITLE
App crashes at runtime with "Unable to find a valid app"

### ISSUE THREAD

**Issue by imkimchi** [jiahaog/nativefier#531]
### Description

I ran `nativefier --name "FB Messenger" "https://messenger.com"`, opened the app and I got this error.

### Details

- Are you nativefying a *public* website?
yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `nativefier --name "FB Messenger" "https://messenger.com"`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v8.9.4`
- OS: `10.13.2`

- Error message / stack trace (if any):

```
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Users/philipyoonshin_spryfit/FB Messenger-darwin-x64/FB Messenger.app/Contents/Resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/Users/philipyoonshin_spryfit/FB Messenger-darwin-x64/FB Messenger.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)

```

**Comment by ronjouch** [comment]
Hey @imkimchi, thanks for the feedback 👍. I cannot reproduce the issue here, so all reproduction hints / suspicions welcome.

**Comment by imkimchi** [comment]
@ronjouch no idea, I didn't do anything special and just ran the command and didn't work out well. and have no experience with electron so I can't help you with reproduction of this problem

**Comment by ronjouch** [comment]
@imkimchi do you have other Nativefied apps that work fine, or that used to work fine? Did you try other options?

**Comment by imkimchi** [comment]
Nope, I tried the command without `--name` option and with other URLs but I still got the same error.

**Comment by imkimchi** [comment]
@ronjouch Nope, I tried the command without `--name` option and with other URLs but I still got the same error.
