### ISSUE TITLE
Can not use URL with protocol ,Error Like :${urlWithProtocol}  is invalid

### ISSUE THREAD

**Issue by caffreycc** [jiahaog/nativefier#534]
### Description

when i run this in cmd : nativefier "www.strangepro.cn:8686
(this a  Connectable website.)
error occur：
throw new Error(`Your Url: "${urlWithProtocol}" is invalid!`);
          ^
Error: Your Url: "www.strangepro.cn:8686/zb_system/strangeproin68062.php" is invalid!
    at normalizeUrl (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\options\options\normalizeUrl.js:21:11)
    at exports.default (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\options\options\optionsMain.js:20:16)
    at C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\build\build\buildMain.js:167:7
    at nextTask (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\node_modules\async\dist\async.js:5310:14)
    at Object.waterfall (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\node_modules\async\dist\async.js:5320:5)
    at buildMain (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\build\build\buildMain.js:164:9)
    at Object.<anonymous> (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\cli.js:95:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

### Steps to reproduce issue

run this in cmd : nativefier "www.strangepro.cn:8686

### Details

- Are you nativefying a *public* website?N
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?Y
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v8.9.3`  
    www.strangepro.cn:8686
- OS: `<OS here>`
    WINDOW 10
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```    throw new Error(`Your Url: "${urlWithProtocol}" is invalid!`);
          ^
Error: Your Url: "www.strangepro.cn:8686/zb_system/strangeproin68062.php" is invalid!
    at normalizeUrl (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\options\options\normalizeUrl.js:21:11)
    at exports.default (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\options\options\optionsMain.js:20:16)
    at C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\build\build\buildMain.js:167:7
    at nextTask (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\node_modules\async\dist\async.js:5310:14)
    at Object.waterfall (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\node_modules\async\dist\async.js:5320:5)
    at buildMain (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\build\build\buildMain.js:164:9)
    at Object.<anonymous> (C:\Users\92030\AppData\Roaming\npm\node_modules\nativefier\lib\cli.js:95:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by ronjouch** [comment]
@caffreycc you need to specify a protocol. `nativefier` **`http://`** `www.strangepro.cn:8686`
