### ISSUE TITLE
Cannot download electron

### ISSUE THREAD

**Issue by maicss** [jiahaog/nativefier#595]
### Description

Windows 10 1703
Both CMD and git-bush

### Steps to reproduce issue
1, npm install nativefier -g
2, `nativefier "web.whatsapp.com"`

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.6.2`
- Version of node.js (run `node --version`): `v10.0.0`
- OS: `Windows 10 1703`
- Error message / stack trace (if any):

```
Downloading tmp-6088-0-electron-v1.8.6-win32-x64.zip
Error: connect ECONNREFUSED 127.0.0.1:443
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
```

**Comment by ronjouch** [comment]
@maicss thanks for the feedback 🙂. We use electron-packager, which in turn depends on electron-download, which [fetches electron releases](https://github.com/electron-userland/electron-download/blob/master/lib/index.js#L29-L36) from `https://github.com/electron/electron/releases/download/...`

- Can you try downloading https://github.com/electron/electron/releases/download/v1.8.6/electron-v1.8.6-win32-x64.zip from your browser?
    - Then, from your command-line, e.g. using cURL?
- Are you using a proxy?
- VPN?
- China Great Firewall?

**Comment by ronjouch** [comment]
> *"But still should not be `127.0.0.1:443`, right?"*

Yeah that confusing, and must be internal electron-dl mumbo-jumbo.

**Comment by xiaoguli** [comment]
nativefier "https://www.baidu.com"
Downloading tmp-3236-0-electron-v3.0.3-darwin-x64.zip
Error: connect ECONNREFUSED 127.0.0.1:443
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }

@ronjouch 
I met the same problem, is there any solution now?

**Comment by xiaoguli** [comment]
@maicss Have you solved your current problem?

**Comment by imydou** [comment]
export ELECTRON_GET_USE_PROXY=1 # 值为1或true
export GLOBAL_AGENT_HTTP_PROXY=http://proxy.example.com:1080
export GLOBAL_AGENT_HTTPS_PROXY=https://proxy.example.com:1080
