### ISSUE TITLE
⌘L causes "TypeError: Error processing argument at index 0, conversion failure from undefined"

### ISSUE THREAD

**Issue by danpritts** [jiahaog/nativefier#633]
### Description

When I press ⌘L (habit, i guess), I get the following error popup:

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at click (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/app/lib/webpack:/app/src/components/menu/menu.js:69:23)
    at MenuItem.click (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)

### Steps to reproduce issue

1) nativefier --name google https://www.google.com/
2) launch app
3) ⌘L

### Details

~/src@precious% nativefier --version
nod7.6.4

~/src@precious% node --version
v10.4.1

MacOS 10.13.4, retina macbook pro, no touchbar.

- Error message / stack trace (if any):

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at click (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/app/lib/webpack:/app/src/components/menu/menu.js:69:23)
    at MenuItem.click (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Users/danno/src/MCloud-darwin-x64/MCloud.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)
```

### thanks
Thanks for nativefier.  I think I am going to like it a lot.

**Comment by bacongravy** [comment]
I can reproduce this issue, too.  I think may have introduced this regression with the refactoring I did to support tabs.  I'll take a closer look later tonight.
