### ISSUE TITLE
Can't read path to icon on Windows

### ISSUE THREAD

**Issue by JacobDB** [jiahaog/nativefier#636]
### Description

No matter how I specify the path, I can't set an icon on Windows. Always throws an error "`Cannot open icon file 'i'`", `i` being the first letter of the path to the icon.

### Steps to reproduce issue

    nativefier --name "Android Messages" --tray --single-instance --icon icon.png "https://messages.android.com"

OR

    nativefier --name "Android Messages" --tray --single-instance --icon "icon.png" "https://messages.android.com"

OR

    nativefier --name "Android Messages" --tray --single-instance --icon C:\Users\Jacob\Downloads\android-messages\icon.png "https://messages.android.com"

OR

    nativefier --name "Android Messages" --tray --single-instance --icon "C:\Users\Jacob\Downloads\android-messages\icon.png" "https://messages.android.com"

OR

    nativefier --name "Android Messages" --tray --single-instance --icon C:/Users/Jacob/Downloads/android-messages/icon.png "https://messages.android.com"

OR

    nativefier --name "Android Messages" --tray --single-instance --icon C:/Users/Jacob/Downloads/android-messages/icon.png "https://messages.android.com"

[icon.png](https://user-images.githubusercontent.com/1123997/41573808-273b5e98-7344-11e8-8341-90c3fccc01f9.png)

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: See above
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v8.9.4`
- OS: `<OS here>` Windows 10 1803
- Error message / stack trace (if any):

```
Error: rcedit.exe failed with exit code 1. Cannot open icon file 'i'
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Jacob\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by JacobDB** [comment]
Appears to be a duplicate of #239, closing.
