### ISSUE TITLE
contains invalid WIN32 path characters

### ISSUE THREAD

**Issue by maicss** [jiahaog/nativefier#637]
### Description

Same version `electron` and `nativefier`, ubuntu and mac os works fine. and on macos, build win32 successfully. 

So I think this maybe not a bug of `nativefier`, but I cannot find help after google it. only find [this issue](https://github.com/electron/electron/issues/8304), and `node -e 'console.log(os.tmpdir())'` output `'C:\\Users\\maics\\AppData\\Local\\Temp'` seems fine. and `npm i -g electron` success. So, it seems not the same error...

THANKS!!

### Steps to reproduce issue

Just Install nativefier and run a cmd

### Details

- Full nativefier command used to build your app: `nativefier "baidu" "https://baidu.com"`
- Version of Nativefier (run `nativefier --version`): `7.6.4`
- Version of node.js (run `node --version`): `9.5.0`
- OS: `Windows 10`
- Error message / stack trace (if any):

```
C:\Users\maics>nativefier "baidu" "https://baidu.com"
  packaging [==============================                    ] 60%Packaging app for platform win32 x64 using electron v2.0.2
{ Error: C:\Users\maics\https:\baidu.com\win32-x64-template contains invalid WIN32 path characters.
    at Object.mkdirs (C:\Users\maics\AppData\Roaming\npm\node_modules\nativefier\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Promise (C:\Users\maics\AppData\Roaming\npm\node_modules\nativefier\node_modules\universalify\index.js:13:12)
    at new Promise (<anonymous>)
    at Object.mkdirs (C:\Users\maics\AppData\Roaming\npm\node_modules\nativefier\node_modules\universalify\index.js:7:14)
    at Packager.createApp (C:\Users\maics\AppData\Roaming\npm\node_modules\nativefier\node_modules\electron-packager\index.js:86:15)
    at download.downloadElectronZip.then.zipPath (C:\Users\maics\AppData\Roaming\npm\node_modules\nativefier\node_modules\electron-packager\index.js:123:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) code: 'EINVAL' }
  packaging [========================================          ] 80%
```

**Comment by ronjouch** [comment]
@maicss see `nativefier --help`:

```
  Usage: nativefier [options] <targetUrl> [dest]
```

So, your final parameter is interpreted as destination folder. You should `nativefier --name baidu "https://baidu.com" C:\Users\maics`

**Comment by maicss** [comment]
Thanks
