### ISSUE TITLE
Exception when using --single-instance

### ISSUE THREAD

**Issue by iblazhko** [jiahaog/nativefier#664]
### Description

When a web site was nativefied with `--single-instance` option, attempt to launch 2nd instance result in an exception.

### Steps to reproduce issue

1. Create wrapper using `--single-instance` flag
2. In a terminal, launch 1st instance. All should be good so far
3. In another terminal, try launching 2nd instance
4. BANG! See exception below. The 1st instance was focused though.

### Details

>- Are you nativefying a *public* website?

Yes, `https://focus.nirvanahq.com/`

>- Feature request?

No

>- Full nativefier command used to build your app:

`nativefier --name "Nirvana" "https://focus.nirvanahq.com" --single-instance`

>- Version of Nativefier (run `nativefier --version`):

`7.6.7`

>- Version of node.js (run `node --version`):

`v8.10.0`

>- OS:

Linux Ubuntu 18.04, 4.15.0-29-generic, GNOME desktop

>- Error message / stack trace (if any):

```
$./nirvana-linux-x64/nirvana

module.js:545
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.emit (/home/iblazhko/nirvana-linux-x64/resources/app/lib/webpack:/app/node_modules/source-map-support/source-map-support.js:454:1)
~ » ./nirvana-linux-x64/nirvana
module.js:545
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/iblazhko/nirvana-linux-x64/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.emit (/home/iblazhko/nirvana-linux-x64/resources/app/lib/webpack:/app/node_modules/source-map-support/source-map-support.js:454:1)
```

**Comment by Cretezy** [comment]
Maybe helpful error:

`(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.`
