### ISSUE TITLE
Unable to create a installer

### ISSUE THREAD

**Issue by liudonghua123** [jiahaog/nativefier#674]
### Description

I created my web app via `nativefier --name ynu_courses -a ia32 --app-version 1.0.0 --build-version 1.0.0 -c --disable-context-menu http://113.55.12.52:50120/`, and then I try build a installer via `electron-installer-windows --src ynu_courses-win32-ia32 --dest dist/installers/`, it gave me the following error.

```
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\LIUD~1.H\AppData\Local\Temp\electron-4968z0C4lHekf0DL\ynu-courses-nativefier-0256db_1.0.0\nuget\ynu-courses-nativefier-0256db.nuspec -BasePath C:\Users\LIUD~1.H\AppData\Local\Temp\electron-4968z0C4lHekf0DL\ynu-courses-nativefier-0256db_1.0.0\ynu-courses-nativefier-0256db -OutputDirectory C:\Users\LIUD~1.H\AppData\Local\Temp\electron-4968z0C4lHekf0DL\ynu-courses-nativefier-0256db_1.0.0\nuget -NoDefaultExcludes
File not found: 'ynu-courses-nativefier-0256db.exe'.

    at err (C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:31:11)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

It seems the electron-installer-windows want to use the `ynu-courses-nativefier-0256db.exe`, not the `ynu-courses`, I rename the file and tried again, then it shown another error as belows.

```
Creating package (this may take a while)
Error: Error releasifying package: Error executing command (Exited with status 4294967295):
C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\squirrel\Squirrel.com --releasify C:/Users/LIUD~1.H/AppData/Local/Temp/electron-197685iyL3U046C44/ynu-courses-nativefier-0256db_1.0.0/nuget/ynu-courses-nativefier-0256db.1.0.0.nupkg --releaseDir C:\Users\LIUD~1.H\AppData\Local\Temp\electron-197685iyL3U046C44\ynu-courses-nativefier-0256db_1.0.0\squirrel --setupIcon C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\icon.ico --loadingGif C:\Users\Liu.D.H\AppData\Roaming\npm\node_modules\electron-installer-windows\resources\animation.gif
System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "C:\Users\Liu.D.H\AppData\Local\Temp\electron-197685iyL3U046C44\ynu-courses-nativefier-0256db_1.0.0\squirrel\Setup.wixobj" "C:\Users\Liu.D.H\AppData\Local\Temp\electron-197685iyL3U046C44\ynu-courses-nativefier-0256db_1.0.0\squirrel\Setup.wxs"'

Output was:
Setup.wxs
C:\Users\Liu.D.H\AppData\Local\Temp\electron-197685iyL3U046C44\ynu-courses-nativefier-0256db_1.0.0\squirrel\Setup.wxs(3) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.ynu-courses-nativefier-0256db.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
C:\Users\Liu.D.H\AppData\Local\Temp\electron-197685iyL3U046C44\ynu-courses-nativefier-0256db_1.0.0\squirrel\Setup.wxs(3) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
```

I also tried building the app via the official installer packager [windows-installer](https://github.com/electron/windows-installer), the build script is belows.

```
// build.js
var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: 'ynu_courses-win32-ia32',
    outputDirectory: 'dist',
    authors: 'Liu.D.H',
    exe: 'ynu-courses.exe'
  });

resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));
```

```
D:\code\weixin\ynu_courses>node build.js
No dice: Failed with exit code: 4294967295
Output:

System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "D:\code\weixin\ynu_courses\dist\Setup.wixobj" "D:\code\weixin\ynu_courses\dist\Setup.wxs"'

Output was:
Setup.wxs
D:\code\weixin\ynu_courses\dist\Setup.wxs(3) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.ynu-courses-nativefier-0256db.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
D:\code\weixin\ynu_courses\dist\Setup.wxs(3) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
```

It was the same error as electron-installer-windows. I think this problem maybe releated to the version info of the binary app.

**Comment by ronjouch** [comment]
@liudonghua123 thanks for the feedback but I don't think that's Nativefier's job. Closing.
