### ISSUE TITLE
Support generating termux android `.apk`

### ISSUE THREAD

**Issue by Austcool-Walker** [jiahaog/nativefier#711]
### Description

<Running nativefier in Termux doesn't generate a `.apk`.>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: <nativefier https://minecraft.net>
- Version of Nativefier (run `nativefier --version`): `v7.6.8`
- Version of node.js (run `node --version`): `v11.2.0`
- OS: `<Android 7.1.1>`
- Error message / stack trace (if any):

```<$ nativefier https://minecraft.net
  inferring [                                                  ] 0%
/data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js:14
  throw new Error(`Untested platform ${platform} detected`);
        ^
Error: Untested platform android detected
    at inferPlatform (/data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/infer/infer/inferOs.js:14:9)
    at exports.default (/data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/options/options/optionsMain.js:21:38)
    at /data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/build/build/buildMain.js:175:9
    at nextTask (/data/data/com.termux/files/usr/lib/node_modules/nativefier/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/data/data/com.termux/files/usr/lib/node_modules/nativefier/node_modules/async/dist/async.js:5334:5)
    at buildMain (/data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/build/build/buildMain.js:171:9)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/nativefier/lib/cli.js:209:16)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
$>```

**Comment by ronjouch** [comment]
@Austcool-Walker nope, but patch welcome.

**Comment by ronjouch** [comment]
Too niche, closing, but patches welcome.
