### ISSUE TITLE
I can not install WhatsApp Web

### ISSUE THREAD

**Issue by darckyn** [jiahaog/nativefier#735]
### Description

Just execute the comand to install and its not work....

### Steps to reproduce issue

Execute in terminal -> nativefier -name WhatsApp web.whatsapp.com

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? YES
- Full nativefier command used to build your app: nativefier -name WhatsApp web.whatsapp.com
- Version of Nativefier (run `nativefier --version`): `v7.6.10`
- Version of node.js (run `node --version`): `v10.15.0`
- OS: `LINUX MINT 19.1`
- Error message / stack trace (if any):

```
Downloading tmp-12929-0-electron-vWhatsApp-linux-x64.zip
Error: GET https://github.com/electron/electron/releases/download/vWhatsApp/electron-vWhatsApp-linux-x64.zip returned 404
Error: Failed to find Electron vWhatsApp for linux-x64 at https://github.com/electron/electron/releases/download/vWhatsApp/electron-vWhatsApp-linux-x64.zip
    at Request.<anonymous> (/usr/lib/node_modules/nativefier/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:182:13)
    at Request.onRequestResponse (/usr/lib/node_modules/nativefier/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```
Thanks in advance.

**Comment by ronjouch** [comment]
@darckyn `--name` or `-n`, not `-name`.
