### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Lascielle** [jiahaog/nativefier#809]
Running into the following issue when I run sudo npm install nativefier -g

**$ sudo npm install nativefier -g**
[sudo] password for *******: 
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
/usr/local/bin/nativefier -> /usr/local/lib/node_modules/nativefier/lib/cli.js

> core-js@2.6.9 postinstall /usr/local/lib/node_modules/nativefier/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ nativefier@7.6.12
added 327 packages from 299 contributors in 5.134s
**:~$ nativefier --help**
Error: Cannot find module 'loglevel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativefier/lib/build/build/buildMain.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativefier/lib/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

It looks like this is because of my current version of nodejs... Any help would be appreciated.

**Comment by mxdpeep** [comment]
it's an issue with your Node.js install:
https://github.com/nodejs/help/issues/1877

**Comment by ronjouch** [comment]
@Lascielle mxdpeep is right: you should look into updating your Node to the latest Node 10, and updating npm.
