### ISSUE TITLE
Error: Cannot open icon file

### ISSUE THREAD

**Issue by robertmylne** [jiahaog/nativefier#841]
I keep getting this error on Windows (any ideas why?):
```
  copying [====================                              ] 40%Packaging app for platform win32 x64 using electron v6.0.3
  packaging [================================                  ] 64%Error: rcedit.exe failed with exit code 1. Cannot open icon file 'C:\Users\Rob\AppData\Local\Temp\tmp-18088Lbq8gkDCBXgj\icon.ico'
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Rob\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  packaging [========================================          ] 79%
```

**Comment by 3ndlos** [comment]
Hi I had some failures keeping it working with powershell - may try cmd instead?

Is the icon a real .ico (may try to convert - never had trouble with .ico converted with https://convertico.com )
Is the path correct? What command do you use?

C:\Users\myuser\Desktop>nativefier -i "cs-logo.ico" "https://mysite.com"
the cs-logo.ico is located at Desktop <- this should work.

**Comment by mxdpeep** [comment]
> Hi I had some failures keeping it working with powershell - may try cmd instead?
> 
> Is the icon a real .ico (may try to convert - never had trouble with .ico converted with https://convertico.com )
> Is the path correct? What command do you use?
> 
> C:\Users\myuser\Desktop>nativefier -i "cs-logo.ico" "https://mysite.com"
> the cs-logo.ico is located at Desktop <- this should work.
or use: https://icoconvert.com
