### ISSUE TITLE
Fatal error : Unable to set icon

### ISSUE THREAD

**Issue by Freeze455** [jiahaog/nativefier#877]
### Description

Hello, I have try to use your project and I have found one error :
`PS C:\Users\Desktop> nativefier --name "Danse de salons" "https://dansesdesalonstmac.fr/"
Downloading tmp-11680-1-SHASUMS256.txt-5.0.10
[============================================>] 100.0% of 4.79 kB (4.79 kB/s)
Packaging app for platform win32 x64 using electron v5.0.10
Error: rcedit.exe failed with exit code 1. Cannot open icon file 'C:\Users\BAPTIS~1\AppData\Local\Temp\tmp-11680KPpIGuHNdVgF\icon.ico'
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

### Steps to reproduce issue
I have just start download. Folder was create in my desktop. Then, this error

### Details

- Are you nativefying a *public* website? Yes
- Full nativefier command used to build your app: `nativefier --name "Danse de salons" "https://dansesdesalonstmac.fr/"`
- Version of node.js (run `node --version`): `v12.13.0`
- OS: `Windows 10`

```
PS C:\Users\Desktop> nativefier --name "Danse de salons" "https://dansesdesalonstmac.fr/"
Downloading tmp-11680-1-SHASUMS256.txt-5.0.10
[============================================>] 100.0% of 4.79 kB (4.79 kB/s)
Packaging app for platform win32 x64 using electron v5.0.10
Error: rcedit.exe failed with exit code 1. Cannot open icon file 'C:\Users\AppData\Local\Temp\tmp-11680KPpIGuHNdVgF\icon.ico'
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by didrip** [comment]
try to run the command at system root (`C:\`)

**Comment by stefanstranger** [comment]
According to the help the icon needs to be of type png but you need to have an icon file to set the icon of the Nativefier app.

HTH
Stefan Stranger

**Comment by Freeze455** [comment]
Hello !
It seems to me that the icon must be set automatically by the application from the target website no? I have nothing more to do normally ..
