### ISSUE TITLE
Microsoft Teams stuck on initialisation with blank screen

### ISSUE THREAD

**Issue by tomaciazek** [jiahaog/nativefier#879]
### Description

After page refresh (manual or caused by application being paused for too long) Microsoft Teams is stuck on a blank initialisation screen.

### Steps to reproduce issue
1. Install nativefier
2. Run `nativefier "https://teams.microsoft.com/" --internal-urls ".*" --name "Teams"`
3. Launch the app
4. Log in to any Teams account
5. Once the application is loaded, refresh the page (twice?)

### Details
nativefier: 7.7.0
node: v12.13.1
OS: macOS Mojave v10.14.6
2 console errors:
angular.min.js:35 Uncaught IPC object is null

```
angular.min.js:113 Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-f892f4aa.js:2113:5777)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-70facf4c.js:9:1239)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-1c4ba51b.js:37:96) undefined
```

![image](https://user-images.githubusercontent.com/15631478/69241481-2ebc0100-0b9f-11ea-8b1a-9502807005ba.png)

**Comment by qdrop17** [comment]
I highly recommend to use the native app that M$ offers: https://teams.microsoft.com/downloads

**Comment by msb217** [comment]
@tomaciazek I've been experiencing this is as well for packaging teams. Same notificationService_startup error. I do edit -> clear app data in order for a hard fix.

@qdrop17 I am unfortunately in multiple organizations at the same time. I use native teams and nativefied teams at the same time to avoid having to cycle browser tabs

**Comment by cosminstirbu** [comment]
We have the same issue and we're forced to use this approach because we also use multiple organizations at the same time.

**Comment by painatas1** [comment]
Hello.
I've this same issue, I already tried a bunch of things without success...If i close the app and re-open it I'll get a white screen and after some time it says that "Teams couldn't connect me" or something like that.
I had to use --clear-cache when creating the app, but each time I've to type in my username and password...

Did you guys find any way to surpass this?

**Comment by cvalouch** [comment]
I was able to get it to work by changing the target url to:
"https://teams.microsoft.com/_\?tenantID\=<my_org_tenant_id>"


as recommended in a separate issue regarding teams.
https://github.com/jiahaog/nativefier/issues/971
I haven't tested screen sharing yet but at least it loads if I quit now.

**Comment by nmargaritis** [comment]
This seems to do the job too
```
nativefier -n "Teams-desktop" --internal-urls "./.*/" "https://teams.microsoft.com/_#"
```
