### ISSUE TITLE
How to create apps for all platforms on Alpine Linux?

### ISSUE THREAD

**Issue by lockwiser** [jiahaog/nativefier#890]
Hello.

OS: `Alpine 3.11`

```bash
# npm -v
6.13.4
# node -v
v12.14.0
# nativefier -v
7.7.0
```
Installed wine:
```
 # apk add wine
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/14) Installing libxau (1.0.9-r0)
(2/14) Installing libbsd (0.10.0-r0)
(3/14) Installing libxdmcp (1.1.3-r0)
(4/14) Installing libxcb (1.13.1-r0)
(5/14) Installing libx11 (1.6.9-r0)
(6/14) Installing libxext (1.3.4-r0)
(7/14) Installing alsa-lib (1.2.1.2-r0)
(8/14) Installing eudev-libs (3.2.9-r1)
(9/14) Installing spirv-tools (2019.5-r0)
(10/14) Installing vkd3d (1.1-r0)
(11/14) Installing xz-libs (5.2.4-r0)
(12/14) Installing libxml2 (2.9.10-r1)
(13/14) Installing wine-libs (4.0.3-r0)
(14/14) Installing wine (4.0.3-r0)
Executing busybox-1.31.1-r8.trigger
OK: 412 MiB in 79 packages
```
Error create app for windows:
```bash
# nativefier --name "Hello" -p "windows" "https://google.com"
Downloading tmp-283-0-electron-v5.0.10-win32-x64.zip
[============================================>] 100.0% of 58.71 MB (10.21 MB/s)
  packaging [=====================================             ] 74%Packaging app for platform win32 x64 using electron v5.0.10
  packaging [========================================          ] 79%Error: Could not find "wine" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: [
    '/usr/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe',
    '/home/google/Hello-win32-x64/Hello.exe',
    '--set-version-string',
    'FileDescription',
    'Hello',
    '--set-version-string',
    'InternalName',
    'Hello',
    '--set-version-string',
    'OriginalFilename',
    'Hello.exe',
    '--set-version-string',
    'ProductName',
    'Hello',
    '--set-version-string',
    'CompanyName',
    'Jia Hao',
    '--set-file-version',
    '1.0.0',
    '--set-product-version',
    '1.0.0'
  ]
}
```

Why is there still no detailed instruction on what to do in this case? There was no answer on google.

**Comment by lockwiser** [comment]
Forced us to use Debian rather than Alpine, which doesn't do multiarch.
