### ISSUE TITLE
Fail to build (primordials)

### ISSUE THREAD

**Issue by kiark** [jiahaog/nativefier#917]
### Description

follow the developer build i get error from external module.

### Steps to reproduce issue
after clone
npm run dev-up-win

### Details

- Are you nativefying a *public* website? yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? yes
- Full nativefier command used to build your app: `no command`
- Version of Nativefier (run `nativefier --version`): `v7.7.1`
- Version of node.js (run `node --version`): `v12.16.1`
- OS: `Windows 10 build 1809`
- Error message / stack trace (if any):
```
nativefier@7.7.1 build U:\app\nativefier
gulp build

[14:14:12] Failed to load external module @babel/register
[14:14:12] Requiring external module babel-register
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (U:\app\nativefier\node_modules\natives\index.js:143:24)
    at Object.req [as require] (U:\app\nativefier\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (U:\app\nativefier\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .js] (U:\app\nativefier\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nativefier@7.7.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativefier@7.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ronjouch** [comment]
@kiark thanks for the feedback. This, and many other things, is fixed in branch `ts` . If you're feeling comfortable, run a dev build following instructions at https://github.com/jiahaog/nativefier/pull/898#issuecomment-581062794 and report issues, prefixing them with `[ts] ` 🙂.
