### ISSUE TITLE
Error: spawn unzip ENOENT

### ISSUE THREAD

**Issue by ProgrammAbel** [jiahaog/nativefier#947]
**Bug description**
I tried to run `nativefier office.com --internal-urls ".*" --verbose` and got the error:
Error during build. Run with --verbose for details. Error: spawn unzip ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn unzip',
  path: 'unzip',
  spawnargs: [
    '-o',
    '/home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip',
    '-d',
    '/home/abelb/Projects/office/linux-x64-template'
  ],
  cmd: 'unzip -o /home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip -d /home/abelb/Projects/office/linux-x64-template'
}

- [Y] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [Y] I searched existing open & closed issues. Yes, my bug is new.
- [Y] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:
1. Run `nativefier --verbose office.com --internal-urls ".*"`
2. Receive error:
Error during build. Run with --verbose for details. Error: spawn unzip ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn unzip',
  path: 'unzip',
  spawnargs: [
    '-o',
    '/home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip',
    '-d',
    '/home/abelb/Projects/office/linux-x64-template'
  ],
  cmd: 'unzip -o /home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip -d /home/abelb/Projects/office/linux-x64-template'
}

**Expected behavior**
For the package to build.

**Actual behavior**
The build failed with the above error message.

**Debug info**
Error during build. Run with --verbose for details. Error: spawn unzip ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn unzip',
  path: 'unzip',
  spawnargs: [
    '-o',
    '/home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip',
    '-d',
    '/home/abelb/Projects/office/linux-x64-template'
  ],
  cmd: 'unzip -o /home/abelb/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.2.0electron-v8.2.0-linux-x64.zip/electron-v8.2.0-linux-x64.zip -d /home/abelb/Projects/office/linux-x64-template'
}

**Context**
 - Nativefier: 8.0.6
 - Node.js: 13.13.0
 - Npm: 6.14.4
 - OS: linux 5.6.3-arch1-1 (x64)
 - Is it a regression? If yes, what's the last working / first broken version? No
 - Additional context: None

**Comment by Ritte88** [comment]
Do you have unzip installed?

**Comment by ProgrammAbel** [comment]
I gave up on this, but FTR yeah, I did.

**Comment by yaua** [comment]
hi yoh. I had the same problem.

**Comment by drewmnoel** [comment]
It looks like you're on Arch, the AUR package was missing the unzip dependency until just now.

**Comment by Ritte88** [comment]
I’m on arch and had to install unzip, works after that.
